//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;

    /// \f[
    /// T_{max}&lt;
    /// \f]
    public partial class ANALYTICS
    {
        /// \f[
        /// T_{max}&lt;
        /// \f]
        public decimal uniqueID { get; set; }

        /// \f[
        /// T_{max}&lt;
        /// \f]
        public decimal ownerID { get; set; }

        /// \f[
        /// T_{max}&lt;
        /// \f]
        public decimal buyerID { get; set; }

        /// \f[
        /// T_{max}&lt;
        /// \f]
        public decimal contentID { get; set; }

        /// \f[
        /// T_{max}&lt;
        /// \f]
        public Nullable<System.DateTime> timestamp { get; set; }

        /// \f[
        /// T_{max}&lt;
        /// \f]
        public Nullable<decimal> credit { get; set; }

        /// \f[
        /// T&lt;
        /// \f]
        public virtual USER USER { get; set; }

        /// \f[
        /// T_{max}&lt;
        /// \f]
        public virtual CONTENT CONTENT { get; set; }

        /// \f[
        /// T_{max}&lt;
        /// \f]
        public virtual USER USER1 { get; set; }
    }
}
